# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Janice's Portfolio"
description: "Powered by Jekyll and GitHub Pages"
author:      "Janice ; Jekyll by Paul Le"

About ME
I am Janice and having  completed a mathematics and business degree in South Africa, I moved to London to work in global financial services. 
I have recently build a global data warehouse for regulatory reporting.
I enjoy learning new things and as I am just about to complete a data analyst course.  
Once complete, I would like to use my skills to analyse data I collect to thereby create more accurate and complete datasets.
Personally, I like to walk, ski, travel with friend and family.
